package:
  name: lightmetrica
  version: 3.0.0

source:
  git_url: git@github.com:hi2p-perim/lightmetrica-v3.git
  git_tag: build_with_conda

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - cppzmq
    - doctest-cpp
    - embree3
    - nlohmann_json
    - pybind11
    - fmt
    - stb

about:
  home: https://github.com/hi2p-perim/lightmetrica-v3
  summary: A research-oriented renderer
  license: MIT
  license_family: MIT
  license_file: LICENSE