package:
  name: lightmetrica
  version: 3.0.0

source:
  #git_url: git@github.com:hi2p-perim/lightmetrica-v3.git
  #git_tag: build_with_conda
  path: ../../lightmetrica-v3-2

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - pip
    - python
    - zeromq
    - cppzmq
    - doctest-cpp
    - embree3
    - glm
    - nlohmann_json
    - pybind11
    - cereal
    - fmt
    - stb
  run:
    - zeromq
    - embree3
    - glm
    - nlohmann_json
    - cereal
    - fmt

about:
  home: https://github.com/hi2p-perim/lightmetrica-v3
  summary: A research-oriented renderer
  license: MIT
  license_family: MIT
  license_file: LICENSE