{% set version = "2.3.2" %}
{% set sha256 = "0753aa9a7b957ab282e0f98be198de11584dc9086fbea9af51616ac09c6f0b9a" %}

package:
  name: doctest-cpp
  version: {{ version }}

source:
  url: https://github.com/onqtam/doctest/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host: []

about:
  home: https://github.com/onqtam/doctest
  summary: The fastest feature-rich C++11/14/17/20 single-header testing framework for unit tests and TDD
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt