{% set version = "2.3.0" %}
{% set sha256 = "8243b7de12b52239fe9235a6aeb4e35ead2247833e4fbc41541774b222717933" %}

package:
  name: openexr
  version: {{ version }}

source:
  url: https://github.com//openexr/openexr/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - cmake-fix.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
  run:
    - zlib

about:
  home: https://github.com/openexr/openexr
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OpenEXR is a high dynamic-range (HDR) image file format developed by Industrial Light & Magic for use in computer imaging applications.
  doc_url: http://www.openexr.com/documentation.html
  dev_url: https://github.com/openexr/openexr
