{% set version = "1.2.2" %}
{% set sha256 = "1921f26d2e1daf9132da3c432e2fd02093ecaedf846e65d7679ddf868c7289c4" %}

package:
  name: cereal
  version: {{ version }}

source:
  url: https://github.com/USCiLab/cereal/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host: []

about:
  home: https://github.com/USCiLab/cereal
  summary: A C++11 library for serialization
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE